# Generated by Django 4.2.6 on 2023-11-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0002_user_department_user_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="semester",
        ),
        migrations.AddField(
            model_name="user",
            name="alumni",
            field=models.CharField(
                choices=[("YES", "YES"), ("NO", "NO")], max_length=10, null=True
            ),
        ),
    ]
