# Generated by Django 4.2.6 on 2023-11-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0003_remove_user_semester_user_alumni"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_profile_image",
        ),
    ]
