# Generated by Django 4.2.7 on 2023-11-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                ("student_id", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("branch", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
