# Generated by Django 4.2.7 on 2023-11-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="alumni",
            fields=[
                ("alum_id", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("domain", models.CharField(max_length=100)),
                ("linkedin", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="sam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("Schedule", models.DateTimeField()),
                ("phone_number", models.IntegerField()),
                (
                    "alum_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sam.alumni"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sam.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="mockinterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=100)),
                ("timing", models.DateTimeField()),
                (
                    "alum_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sam.alumni"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sam.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="avf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courses", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
                (
                    "alum_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sam.alumni"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sam.student"
                    ),
                ),
            ],
        ),
    ]
