# Generated by Django 4.2.6 on 2023-11-06 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sam", "0002_alumni_sam_mockinterview_avf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avf",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="sam",
            name="student_id",
        ),
        migrations.AlterField(
            model_name="avf",
            name="alum_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="mockinterview",
            name="alum_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friends",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mockinterview",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person2persons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sam",
            name="alum_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="alumni",
        ),
        migrations.DeleteModel(
            name="student",
        ),
    ]
